### ISSUE TITLE
 Duvidas sobre funcionamento do Login Admin/Funcionario

### ISSUE THREAD

**Issue by AlexeiMardegan** [gotou-eiji/tcc-reserva-carro#1]
Fica aqui arquivado a atual dúvida de como vamos fazer um login que apenas administradores veem todas as funções e funcionários são limitados a algumas páginas.

**Comment by gotou-eiji** [comment]
Na página principal seria o login do usuário, depois desenvolver um botão que levaria para o login do administrador.
