### ISSUE TITLE
Deixar só um botão do Inicio na Home.

### ISSUE THREAD

**Issue by AlexeiMardegan** [gotou-eiji/tcc-reserva-carro#17]
Em vez de ter dois botões cujo são elas "Inicio Do Site" e "Inicio Do Painel" tirar elas e fazer um Ícone de Casa para ser o Home.
![image](https://github.com/gotou-eiji/tcc-reserva-carro/assets/76541124/b52c28d6-d876-48e0-bf15-cefa6eda11c0)

**Comment by gotou-eiji** [comment]
Problema resolvido com um botão (que futuramente será uma logo) que direciona para a home. Os dois botões "Início do site" e "Início do Painel" foram removidos.
