### ISSUE TITLE
Tirar os dois botões "Cadastrar Funcionario"  e "Listar Funcionario" e deixar apenas um botão.

### ISSUE THREAD

**Issue by AlexeiMardegan** [gotou-eiji/tcc-reserva-carro#18]
Este único botão será chamado "Funcionário", ele vai Listar os Funcionários e em cima terá um botão de adicionar Login e terá dois Ícones, um ícone de lápis para Editar e um ícone de lixeira.

**Comment by gotou-eiji** [comment]
Problema resolvido, agora o sistema terá apenas um botão chamado "Funcionário" que irá ter tanto a listagem quanto um botão que será direcionamento para o cadastro do mesmo.
