### ISSUE TITLE
 Como será feito as edições de informações dos funcionários

### ISSUE THREAD

**Issue by AlexeiMardegan** [gotou-eiji/tcc-reserva-carro#2]
Há duas opções,  apenas o administrador irá conseguir editar as informações dos funcionários tais como (NOME,TELEFONE,EMAIL,FUNÇÃO.etc) ou a outra opção seria o funcionário ter seu perfil e assim podendo editar ele mesmo os campos, porém apenas TELEFONE e EMAIL.

**Comment by gotou-eiji** [comment]
Só o administrador conseguirá editar as informações do usuário, através de uma solicitação.
