### ISSUE TITLE
Mudar as colunas da tabela de carro  no Banco de Dados para poder adicionar mais atributos referente ao seu formulário carro.

### ISSUE THREAD

**Issue by AlexeiMardegan** [gotou-eiji/tcc-reserva-carro#20]
NÃO PODE ESQUECER 
O formulário Carro precisa de mais atributos e então precisa mudar sua tabela no Banco de Dados.

**Comment by gotou-eiji** [comment]
Banco de dados reestruturado.

**Comment by AlexeiMardegan** [comment]
Precisa botar cor boboca
